apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 7
  selector:
    matchExpressions:
      - { key: env, operator: In, values: [ production ] }
      - { key: country, operator: In, values: [ India ] }
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
        region: IN
        dc: "2"
    spec:
      containers:
      - name: myweb-cont
        image: httpd


